import { createSlice } from '@reduxjs/toolkit';

const initialState =[
    {
        id: "1",
        firstName: "John",
        lastName: "Doe",
        startDate: "2022-01-01",
        departmentName: "Design",
        birthDate: "1990-05-15",
        streetAddress: "123 Main St",
        cityName: "Anytown",
        stateName: "California",
        postalCode: "12345",
    },
    {
        id: "2",
        firstName: "Jane",
        lastName: "Smith",
        startDate: "2021-12-15",
        departmentName: "Legal",
        birthDate: "1985-09-20",
        streetAddress: "456 Elm St",
        cityName: "Othertown",
        stateName: "New York",
        postalCode: "54321",
    },
    {
        id: "3",
        firstName: "Michael",
        lastName: "Johnson",
        startDate: "2022-02-10",
        departmentName: "Sales",
        birthDate: "1995-04-30",
        streetAddress: "789 Oak St",
        cityName: "AnycityName",
        stateName: "Texas",
        postalCode: "67890",
    },
    {
        id: "4",
        firstName: "Emily",
        lastName: "Brown",
        startDate: "2022-03-05",
        departmentName: "Marketing",
        birthDate: "1992-08-25",
        streetAddress: "101 Pine St",
        cityName: "Sometown",
        stateName: "Florida",
        postalCode: "54321",
    },
    {
        id: "5",
        firstName: "David",
        lastName: "Lee",
        startDate: "2022-04-20",
        departmentName: "Human Resources",
        birthDate: "1988-11-10",
        streetAddress: "202 Maple St",
        cityName: "Anothertown",
        stateName: "Washington",
        postalCode: "98765",
    },
    {
        id: "6",
        firstName: "Olivia",
        lastName: "Garcia",
        startDate: "2021-11-30",
        departmentName: "Legal",
        birthDate: "1993-03-18",
        streetAddress: "303 Cedar St",
        cityName: "NewcityName",
        stateName: "Illinois",
        postalCode: "13579",
    },
    {
        id: "7",
        firstName: "Sophia",
        lastName: "Martinez",
        startDate: "2022-05-25",
        departmentName: "Sales",
        birthDate: "1991-07-12",
        streetAddress: "404 Walnut St",
        cityName: "cityNameville",
        stateName: "Massachusetts",
        postalCode: "24680",
    },
    {
        id: "8",
        firstName: "Ethan",
        lastName: "Lopez",
        startDate: "2022-06-30",
        departmentName: "Engineering",
        birthDate: "1994-02-28",
        streetAddress: "505 Birch St",
        cityName: "Techtown",
        stateName: "California",
        postalCode: "97531",
    },
    {
        id: "9",
        firstName: "Mia",
        lastName: "Hernandez",
        startDate: "2022-07-15",
        departmentName: "Marketing",
        birthDate: "1996-09-05",
        streetAddress: "606 Oak St",
        cityName: "Helpville",
        stateName: "New York",
        postalCode: "36987",
    },
    {
        id: "10",
        firstName: "Aiden",
        lastName: "Gonzalez",
        startDate: "2022-08-20",
        departmentName: "Design",
        birthDate: "1997-12-25",
        streetAddress: "707 Pine St",
        cityName: "Testtown",
        stateName: "Georgia",
        postalCode: "74563",
    },
    {
        id: "11",
        firstName: "Isabella",
        lastName: "Rodriguez",
        startDate: "2022-09-10",
        departmentName: "Engineering",
        birthDate: "1998-04-15",
        streetAddress: "808 Elm St",
        cityName: "Educateville",
        stateName: "New Jersey",
        postalCode: "12345",
    },
    {
        id: "12",
        firstName: "James",
        lastName: "Perez",
        startDate: "2022-10-05",
        departmentName: "Legal",
        birthDate: "1999-06-20",
        streetAddress: "909 Maple St",
        cityName: "Lawtown",
        stateName: "Utah",
        postalCode: "54321",
    },
    {
        id: "13",
        firstName: "Camila",
        lastName: "Turner",
        startDate: "2022-11-15",
        departmentName: "Sales",
        birthDate: "2000-08-30",
        streetAddress: "1010 Oak St",
        cityName: "Shipville",
        stateName: "Colorado",
        postalCode: "67890",
    },
    {
        id: "14",
        firstName: "Mateo",
        lastName: "Scott",
        startDate: "2022-12-20",
        departmentName: "Sales",
        birthDate: "2001-10-25",
        streetAddress: "1111 Pine St",
        cityName: "Securetown",
        stateName: "Indiana",
        postalCode: "13579",
    },
    {
        id: "15",
        firstName: "Luna",
        lastName: "Price",
        startDate: "2023-01-15",
        departmentName: "Marketing",
        birthDate: "2002-12-10",
        streetAddress: "1212 Elm St",
        cityName: "Promotetown",
        stateName: "Oregon",
        postalCode: "98765",
    },
    {
        id: "16",
        firstName: "Lucas",
        lastName: "Watson",
        startDate: "2023-02-20",
        departmentName: "Human Resources",
        birthDate: "2003-03-18",
        streetAddress: "1313 Maple St",
        cityName: "Connecttown",
        stateName: "Wyoming",
        postalCode: "24680",
    },
    {
        id: "17",
        firstName: "Hazel",
        lastName: "Brooks",
        startDate: "2023-03-25",
        departmentName: "Design",
        birthDate: "2004-04-15",
        streetAddress: "1414 Oak St",
        cityName: "Broadcastville",
        stateName: "Montana",
        postalCode: "36987",
    },
    {
        id: "18",
        firstName: "Henry",
        lastName: "Sanders",
        startDate: "2023-04-30",
        departmentName: "Design",
        birthDate: "2005-05-20",
        streetAddress: "1515 Pine St",
        cityName: "Createtown",
        stateName: "Delaware",
        postalCode: "97531",
    },
];

export const dataTable = createSlice({
    name: 'dataTable',
    initialState,
    reducers: {
        addRow: (state, action) => {
            state.push(action.payload);
        },
        deleteRow: (state, action) => {
            return state.filter(row => row.id !== action.payload.id);
        },
    },
});

export const { addRow, deleteRow } = dataTable.actions;
export default dataTable.reducer;